### PR TITLE
Use non-blocking random number device for AES-Key

### PR DESCRIPTION
**Pull request by thogaw**
/dev/random is blocking if entropy-pool is empty, which is will cause failures on the healthchecks.

From random(4) manpage:

```
The /dev/random device is a legacy interface which dates back to
a time where the cryptographic primitives used in the
implementation of /dev/urandom were not widely trusted.  It will
return random bytes only within the estimated number of bits of
fresh noise in the entropy pool, blocking if necessary.
/dev/random is suitable for applications that need high quality
randomness, and can afford indeterminate delays.
```

For this reason /dev/random is not suitable for the healthcheck of pgpool.

The drawback is a slightly less secure, temporary AES-Key which is generated for each run the scripts anyway.

The benefit is, that /dev/urandom is non-blocking and so it resolves a lot of issues you habe with the docker image and helm charts using this image.

### CODE REVIEW

**Comment by fmulero** [comment]
Hi @thogaw, thanks a lot  for your contribution.

To be honest I am little bit rookie about this particular topic. Everything I read points that `/dev/urandom` generates predictable results when you are running it in a "fresh" instance (recently installed and booted) and a container is very close to that. Could you share more information about this topic and/or a way to reproduce the healthcheck issue you mentioned?

Regards

**Comment by fmulero** [comment]
Could [this issue](https://github.com/bitnami/bitnami-docker-pgpool/issues/35#issuecomment-997240157) be related to?

**Comment by thogaw** [comment]
> Could [this issue](https://github.com/bitnami/bitnami-docker-pgpool/issues/35#issuecomment-997240157) be related to?

This is exactly the issue. We encountered the same in our current project and researched for the root cause ;)

The cause in our case was an empty entropy-pool on one of your k8s cluster nodes.

**Comment by thogaw** [comment]
> Hi @thogaw, thanks a lot for your contribution.
> 
> To be honest I am little bit rookie about this particular topic. Everything I read points that `/dev/urandom` generates predictable results when you are running it in a "fresh" instance (recently installed and booted) and a container is very close to that. Could you share more information about this topic and/or a way to reproduce the healthcheck issue you mentioned?
> 
> Regards

In the container this is true. But the random number generator block devices are "mounted" from the host operating system. So there should be enough seed to provide enough random events.

**Comment by fmulero** [comment]
LGTM

**Pull request merged**
